--DATABASE OLUŞTURULMASI
CREATE DATABASE ENOCA

--TABLOLAR VE BİRBİRLERİ İLE OLAN İLİŞKİLERİNİN OLUŞTURULMASI OLUŞTURULMASI
CREATE TABLE PERSONEL(
    Personel_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    AD VARCHAR(50) NOT NULL,
    SOYAD VARCHAR(50) NOT NULL,
    POZISYON VARCHAR(50) NULL,

)

CREATE TABLE PROJE(
    Proje_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    PROJEAD VARCHAR(50) NOT NULL,
    SORUMLUPERSONELID INT FOREIGN KEY REFERENCES PERSONEL(Personel_ID) NOT NULL,
    BASLAMATARIH DATETIME NOT NULL,
    BITISTARIH DATETIME NULL,

)

--DEĞERLERİN GİRİLMESİ
INSERT INTO PERSONEL (AD, SOYAD,POZISYON) VALUES ('Osman', 'Cagri','Frontend Team Leader')
INSERT INTO PERSONEL (AD, SOYAD,POZISYON) VALUES ('Safak', 'Akin','Backand Developer')
INSERT INTO PERSONEL (AD, SOYAD,POZISYON) VALUES ('Mert', 'Deke','Software Developer')

DECLARE @PersonelIDosman INT
SELECT @PersonelIDosman = Personel_ID FROM PERSONEL WHERE AD = 'Osman'
DECLARE @PersonelIDmert INT
SELECT @PersonelIDmert = Personel_ID FROM PERSONEL WHERE AD = 'Mert'

INSERT INTO PROJE (PROJEAD, SORUMLUPERSONELID,BASLAMATARIH,BITISTARIH) VALUES 
            ('Asya', (@PersonelIDosman), 
             CONVERT(datetime,'2024.01.01 08:00:00',102), 
             CONVERT(datetime,'2024.06.01 08:00:00',102))

INSERT INTO PROJE (PROJEAD, SORUMLUPERSONELID,BASLAMATARIH,BITISTARIH) VALUES 
            ('Avrupa', (@PersonelIDmert),
            CONVERT(datetime,'2024.06.01 08:00:00',102),
            CONVERT(datetime,'2025.01.01 08:00:00',102))

INSERT INTO PROJE (PROJEAD, SORUMLUPERSONELID,BASLAMATARIH,BITISTARIH) VALUES 
            ('Guney Amreika', (@PersonelIDosman),
            CONVERT(datetime,'2025.01.01 08:00:00',102),
            CONVERT(datetime,'2026.01.01 08:00:00',102))

